# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c51184c99d1b1c31e41a600fa008912fdf252ae78d2c07faf85c91a4e03f234cc2aacc5a509a9daca4bd9a0f848fa5b1047a0ac4488aa5736523c59f5be713dd

test:
  secret_key_base: b86c0d2c4dd76a9f5a9cc047ad26f251fbcf63c79ca1da8a4a8e6997edf2edcdd7dcb9869927487bd82232e217f61b5861049528319d1933ca4f1cc9f5f52dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
